### PR TITLE
Fix eslint and update travis for run it.

### PR DESCRIPTION
**Pull request by caueops**
These are small changes to:
1. Fix the eslint settings.
2. Update the travis-ci to run `npm run lint`
3. Use the binaries that are on `node_modules` rather than global

### CODE REVIEW

**Comment by mamal72** [comment]
@cauealves Thank you so much for your PR. There are some things to mention:
1. We are using `airbnb` JS config for `eslint`. It's better to not just removing it.
2. Why did you removed node versions from `travis.yml` file? I think it's better to check multiple versions instead of only latest stable version. _P.S: Running lint in CI was a good hint. I forgot it. I think it's better to add `npm run lint && ...` to `package.json`'s test script_ 👍 
3. Node is running the commands from local installation if it found any. There is no need to point to the `node_modules/.bin`.

**Comment by caueops** [comment]
Hello @mamal72, thanks for merged.

See,
1. I remove the `airbnb` plugin because I noticed that there are several things that are not according to the style guide them. But if it is really to follow, just keep it. :)
2. Because I do not believe there is a need for your project be testing with multiple versions.You use simple functions for build a component. But anyway, it is not more cost to keep the other versions.

**Comment by mamal72** [comment]
@cauealves: You're welcome. Thanks for all your efforts. 😄👍 
1. Yup. There were some problems before and now they are fixed. Thanks for mentioning. I almost forgot about my lint script. 😑👍
2. Hm... As the current version of LTS node is `4.x`, and the current latest stable is `6.x`, I think it's necessary to check these versions at least. I can remove the `5.x` version too but as it's not taking so much time to run in Travis CI (~1 minutes), I think it's not harming to keep it there too. 🤔

**Comment by caueops** [comment]
Yeah, nice job for solve the problems 💃 

I think we can keep the versions.

**Pull request merged**
